### ISSUE TITLE
ethmainnet: fix becanblock file

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11239]
```
[INFO] [07-19|07:46:43.384] Timings (slower than 50ms)               Execution=298ms BlockValidation=1.2419496s commit=186.086µs alloc=12.6GB sys=26.8GB
[DBUG] [07-19|07:46:43.384] [6/6 Finish] Prune done                  in=6.712µs
[DBUG] [07-19|07:46:43.384] [5/6 TxLookup] Prune done                in=3.107µs
[DBUG] [07-19|07:46:43.394] Discarded transactions                   count=96 pending=96 baseFee=0 queued=0
[DBUG] [07-19|07:46:43.396] [4/6 Execution] Prune done               in=12.40536ms
[DBUG] [07-19|07:46:43.396] [3/6 Senders] Prune done                 in=5.334µs
[DBUG] [07-19|07:46:43.396] [2/6 BlockHashes] Prune done             in=1.281µs
[DBUG] [07-19|07:46:43.396] [snapshots] Prune Blocks                 to=20337000 limit=100
[DBUG] [07-19|07:46:43.396] [1/6 Snapshots] Prune done               in=26.056µs
[DBUG] [07-19|07:46:43.755] Incremented state history                elapsed=78.68µs preverifiedValidators=1495538
[DBUG] [07-19|07:46:43.755] Imported chain segment                   app=caplin stage=ForkChoice hash=0x036e736e518623e416945ceb1c2ad56e3fb494e08312f70507f066d2cd6004bd slot=9545931 alloc=13.3GB sys=26.8GB
[DBUG] [07-19|07:46:43.756] clstage finish                           app=caplin stage=ForkChoice in=736.294302ms next=ListenForForks
[DBUG] [07-19|07:46:43.756] clstage finish                           app=caplin stage=ListenForForks in=4.348µs next=CleanupAndPruning
[DBUG] [07-19|07:46:43.756] clstage finish                           app=caplin stage=CleanupAndPruning in=10.881µs next=SleepForSlot
[DBUG] [07-19|07:46:43.756] sleeping until next slot                 app=caplin stage=SleepForSlot slot=9545932 time=2024-07-19T07:46:47+0000 dur=3.243689208s
[DBUG] [07-19|07:46:47.000] clstage finish                           app=caplin stage=SleepForSlot in=3.243810076s next=CatchUpBlocks
[DBUG] [07-19|07:46:47.052] [db] open                                label=inMem sizeLimit=512MB pageSize=4096
[DBUG] [07-19|07:46:47.052] waiting for blocks...                    app=caplin stage=CatchUpBlocks seenSlot=9545931 targetSlot=9545932 requestedSlots=1
[INFO] [07-19|07:46:48.001] P2P                                      app=caplin peers=3
[DBUG] [07-19|07:46:48.031] [p2p] Discovery table                    protocol=any version=v5 len=149 live=147 unsol=0 ips=213 db=0 reval=1709 RPC timeout=427
[DBUG] [07-19|07:46:48.640] Received block via gossip                slot=9545932
[DBUG] [07-19|07:46:48.650] Block scheduled for later processing     slot=9545932 block=20339173
[DBUG] [07-19|07:46:48.657] Received blob sidecar via gossip         index=0 size=128KB
[DBUG] [07-19|07:46:48.704] Received blob sidecar via gossip         index=1 size=128KB
[DBUG] [07-19|07:46:48.736] Received blob sidecar via gossip         index=2 size=128KB
[DBUG] [07-19|07:46:48.840] Received blob sidecar via gossip         index=3 size=128KB
[DBUG] [07-19|07:46:48.854] Received blob sidecar via gossip         index=4 size=128KB
[DBUG] [07-19|07:46:48.857] Received blob sidecar via gossip         index=5 size=128KB
[DBUG] [07-19|07:46:48.892] UnwindTo                                 block=20339172 stack="[sync.go:173 ethereum_execution.go:196 ethereum_execution.go:261 kv_temporal.go:125 ethereum_execution.go:260 execution_client.go:63 chain_reader.go:343 execution_client_direct.go:71 on_block.go:116 block_service.go:192 block_service.go:244 map.go:477 block_service.go:237 asm_amd64.s:1695]"
[DBUG] [07-19|07:46:48.892] Execution ForkValidator.ValidatePayload  foundCanonical=true currentHash=0x0cc646a0d573911b5958527aabaae548d472e07e4e14b1848df9d31fda2aa9e3 unwindPoint=20339172
[DBUG] [07-19|07:46:49.713] clstage finish                           app=caplin stage=CatchUpBlocks in=2.713276499s next=ForkChoice
[DBUG] [07-19|07:46:49.716] OnBlock                                  elapsed=829.481364ms
[DBUG] [07-19|07:46:49.749] Caplin is sending forkchoice             app=caplin stage=ForkChoice
[DBUG] [07-19|07:46:49.749] UnwindTo                                 block=20339172 stack="[sync.go:173 forkchoice.go:292 asm_amd64.s:1695]"
[INFO] [07-19|07:46:49.749] [updateForkchoice] Fork choice update: flushing in-memory state (built by previous newPayload)
[DBUG] [07-19|07:46:49.752] import operations                        time=35.998923ms
[DBUG] [07-19|07:46:49.835] [1/6 Snapshots] DONE                     in=8.638µs
[DBUG] [07-19|07:46:49.835] [2/6 BlockHashes] DONE                   in=1.986µs
[DBUG] [07-19|07:46:49.843] [3/6 Senders] DONE                       in=8.356823ms
[DBUG] [07-19|07:46:49.843] [4/6 Execution] DONE                     in=148.385µs
[DBUG] [07-19|07:46:49.858] [5/6 TxLookup] DONE                      in=14.234904ms
[DBUG] [07-19|07:46:49.858] [6/6 Finish] DONE                        in=31.062µs
[INFO] [07-19|07:46:49.858] RPC Daemon notified of new headers       from=20339172 to=20339173 amount=1 hash=0x724aa80443f9fcf4871b28c9a3e5401778d5a4c350971fd449ace48d820689a7 header sending=10.357µs log sending=160ns
[INFO] [07-19|07:46:49.858] head updated                             number=20339173 hash=0x724aa80443f9fcf4871b28c9a3e5401778d5a4c350971fd449ace48d820689a7
[INFO] [07-19|07:46:49.867] Timings (slower than 50ms)               BlockValidation=715.020988ms FlushExtendingFork=85.591345ms commit=267.636µs alloc=14.2GB sys=26.8GB
[DBUG] [07-19|07:46:49.868] [6/6 Finish] Prune done                  in=14.487µs
[DBUG] [07-19|07:46:49.868] [5/6 TxLookup] Prune done                in=3.835µs
[DBUG] [07-19|07:46:49.876] Discarded transactions                   count=116 pending=113 baseFee=0 queued=3
[DBUG] [07-19|07:46:49.882] [4/6 Execution] Prune done               in=14.528132ms
[DBUG] [07-19|07:46:49.882] [3/6 Senders] Prune done                 in=5.526µs
[DBUG] [07-19|07:46:49.882] [2/6 BlockHashes] Prune done             in=1.4µs
[DBUG] [07-19|07:46:49.882] [snapshots] Prune Blocks                 to=20337000 limit=100
[DBUG] [07-19|07:46:49.882] [1/6 Snapshots] Prune done               in=53.574µs
[DBUG] [07-19|07:46:50.282] Incremented state history                elapsed=119.189µs preverifiedValidators=1495538
[INFO] [07-19|07:46:50.601] State processing progress                slot=8599969 blk/sec=22.05
[DBUG] [07-19|07:46:51.114] Imported chain segment                   app=caplin stage=ForkChoice hash=0x8c824ecb865f7a7fde996e102fee225d5477c3e9308f66be76a690efc00c62c8 slot=9545932 alloc=15.0GB sys=26.8GB
[DBUG] [07-19|07:46:51.115] clstage finish                           app=caplin stage=ForkChoice in=1.401848843s next=ListenForForks
[DBUG] [07-19|07:46:51.115] clstage finish                           app=caplin stage=ListenForForks in=3.878µs next=CleanupAndPruning
[DBUG] [07-19|07:46:51.115] clstage finish                           app=caplin stage=CleanupAndPruning in=11.639µs next=SleepForSlot
[DBUG] [07-19|07:46:51.115] sleeping until next slot                 app=caplin stage=SleepForSlot slot=9545933 time=2024-07-19T07:46:59+0000 dur=7.884601781s
panic: runtime error: slice bounds out of range [13550:480] [recovered]
	panic: file: v1-008600-008700-beaconblocks.seg, runtime error: slice bounds out of range [13550:480], [decompress.go:670 panic.go:770 panic.go:154 decompress.go:703 beacon_block_reader.go:119 state_antiquary.go:268 state_antiquary.go:87 asm_amd64.s:1695]

goroutine 1019025 [running]:
github.com/erigontech/erigon-lib/seg.(*Getter).Next.func1()
	/home/ubuntu/erigon/erigon-lib/seg/decompress.go:670 +0xf4
panic({0x2927060?, 0xc45cb384f8?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/erigontech/erigon-lib/seg.(*Getter).Next(0xc1bfbc98b8, {0x0, 0x0, 0x0})
	/home/ubuntu/erigon/erigon-lib/seg/decompress.go:703 +0x5b2
github.com/erigontech/erigon/turbo/snapshotsync/freezeblocks.(*beaconSnapshotReader).ReadBlockBySlot(0xc27af4e920, {0x8339c0?, 0xc3bcc2a000?}, {0x3352ef8, 0xc3108cfd10}, 0x8339c1)
	/home/ubuntu/erigon/turbo/snapshotsync/freezeblocks/beacon_block_reader.go:119 +0x78a
github.com/erigontech/erigon/cl/antiquary.(*Antiquary).IncrementBeaconState(0xc1857fc820, {0x332bd80, 0xc277e4b4f0}, 0x91a5bf)
	/home/ubuntu/erigon/cl/antiquary/state_antiquary.go:268 +0xdf9
github.com/erigontech/erigon/cl/antiquary.(*Antiquary).loopStates(0xc1857fc820, {0x332bd80, 0xc277e4b4f0})
	/home/ubuntu/erigon/cl/antiquary/state_antiquary.go:87 +0x2d7
created by github.com/erigontech/erigon/cl/antiquary.(*Antiquary).Loop in goroutine 1018888
	/home/ubuntu/erigon/cl/antiquary/antiquary.go:188 +0x103f
exit status 2
```

**Comment by Giulio2002** [comment]
This is ju
