### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference Erigon3

### ISSUE THREAD

**Issue by directsyndikat** [erigontech/erigon#11384]
#### System information

Erigon version: `./erigon --version`

OS & Version: Linux ubuntu 22.04

Commit hash: 
./build/bin/erigon --chain=bor-mainnet --bor.heimdall=https://heimdall-api.polygon.technology/ --prune.mode=full --torrent.download.rate=512mb --db.read.concurrency=2048 --rpc.batch.concurrency=80 --sync.loop.block.limit=20000 --batchSize=4G --sync.loop.prune.limit=20000

Chain: Polygon

Expected behaviour
After sync completed, stopped node and restart with the following command:
`./build/bin/erigon --chain=bor-mainnet --bor.heimdall=https://heimdall-api.polygon.technology/ --prune.mode=full --torrent.download.rate=512mb --db.read.concurrency=2048 --rpc.batch.concurrency=80 --sync.loop.block.limit=20000 --batchSize=4G --sync.loop.prune.limit=20000 --log.console.verbosity=info --http --http.api=debug,eth,net,web3,bor,trace --http.port=8545 --http.addr=0.0.0.0 --ws=true --ws.port=8546`

Expected to start and enable API functions, http and ws RPC.

 Actual behaviour:
```
 8158434cf8469f50940927768a9c59ecb07a136a7@127.0.0.1:30303 name=erigon/v3.00.0-alpha1-6df3f87d/linux-arm64/go1.22.5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0x15ff1d8]

goroutine 36869 [running]:
github.com/erigontech/erigon/polygon/bor.ComputeHeadersRootHash({0x4448106008, 0x200, 0x528ba20?})
        github.com/erigontech/erigon/polygon/bor/bor.go:1450 +0xb8
github.com/erigontech/erigon/polygon/bor.(*Bor).GetRootHash(0x4436f76780, {0x2f8b100, 0x528ba20}, {0xf03595599068, 0x42e01d2c40}, 0x39293a6, 0x39295a5)
        github.com/erigontech/erigon/polygon/bor/bor.go:1435 +0x310
github.com/erigontech/erigon/polygon/bor.(*Bor).Start.func1(0x39293a6, 0x39295a5)
        github.com/erigontech/erigon/polygon/bor/bor.go:1317 +0xdc
github.com/erigontech/erigon/polygon/bor.FinalityAPIFunc.GetRootHash(0xf03595599120?, 0x42e01d2c00?, 0x42e37089a0?)
        github.com/erigontech/erigon/polygon/bor/bor.go:1302 +0x2c
github.com/erigontech/erigon/polygon/bor/finality.borVerify({0x2f8b650, 0x42e37089a0}, 0x40007c4b60, 0x39293a6, 0x39295a5, {0x41dda1a732, 0x40}, 0x1)
        github.com/erigontech/erigon/polygon/bor/finality/bor_verifier.go:94 +0x178
github.com/erigontech/erigon/polygon/bor/finality.fetchWhitelistCheckpoint({0x2f8b650, 0x42e37089a0}, {0x2fa9348?, 0x4433ff2a50?}, 0x44473d1e80, 0x40007c4b60)
        github.com/erigontech/erigon/polygon/bor/finality/whitelist_helpers.go:61 +0x27c
github.com/erigontech/erigon/polygon/bor/finality.handleWhitelistCheckpoint({0x2f8b650?, 0x42e37089a0?}, {0x2fa9348?, 0x4433ff2a50?}, 0x441756cbc8?)
        github.com/erigontech/erigon/polygon/bor/finality/whitelist.go:182 +0x58
github.com/erigontech/erigon/polygon/bor/finality.retryHeimdallHandler(0x2c5e168, 0x40007c4b60, 0x174876e800, 0x6fc23ac00, {0x27447cc, 0x14})
        github.com/erigontech/erigon/polygon/bor/finality/whitelist.go:135 +0x98
github.com/erigontech/erigon/polygon/bor/finality.RetryHeimdallHandler(...)
        github.com/erigontech/erigon/polygon/bor/finality/whitelist.go:117
github.com/erigontech/erigon/polygon/bor/finality.startCheckpointWhitelistService(...)
        github.com/erigontech/erigon/polygon/bor/finality/whitelist.go:82
created by github.com/erigontech/erigon/polygon/bor/finality.Whitelist in goroutine 1
        github.com/erigontech/erigon/polygon/bor/finality/whitelist.go:63 +0x18c
```

Steps to reproduce the behaviour
Sync with the command mentioned above, stop the node and restart with second command.

Can't find a workaround within the issues

**Comment by AskAlexSharov** [comment]
@directsyndikat hi. can you please `git pull` and re-start on latest version - i added additional logging for this case. and show logs pls.

**Comment by AskAlexSharov** [comment]
same as of https://github.com/erigontech/erigon/issues/11314

**Comment by AskAlexSharov** [comment]
oh, i can reproduce now

**Comment by AskAlexSharov** [comment]
probably fixed by https://github.com/erigontech/erigon/pull/11389

**Comment by directsyndikat** [comment]
> git pull

```
root@Ubuntu-2204-jammy-arm64-base ~/erigon # git pull
Already up to date.
```

im starting Erigon3 with the following flags:
```
./build/bin/erigon 
--chain=bor-mainnet 
--bor.heimdall=https://heimdall-api.polygon.technology/ 
--prune.mode=full 
--torrent.download.rate=512mb 
--db.read.concurrency=2048 
--rpc.batch.concurrency=80 
--sync.loop.block.limit=20000 
--batchSize=4G 
--sync.loop.prune.limit=20000 
--http.api=debug,eth,net,web3,bor,trace 
--ws=true
```

Error:
```
INFO[07-29|16:26:52.005] [1/9 Snapshots] Requesting downloads 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0x15ff1d8]

goroutine 17478 [running]:
github.com/erigontech/erigon/polygon/bor.ComputeHeadersRootHash({0x400063d988, 0x300, 0x528ba20?})
        github.com/erigontech/erigon/polygon/bor/bor.go:1450 +0xb8
github.com/erigontech/erigon/polygon/bor.(*Bor).GetRootHash(0x442ab30960, {0x2f8b100, 0x528ba20}, {0xf21dc8617fd8, 0x4453b86100}, 0x392c2a6, 0x392c5a5)
        github.com/erigontech/erigon/polygon/bor/bor.go:1435 +0x310
github.com/erigontech/erigon/polygon/bor.(*Bor).Start.func1(0x392c2a6, 0x392c5a5)
        github.com/erigontech/erigon/polygon/bor/bor.go:1317 +0xdc
github.com/erigontech/erigon/polygon/bor.FinalityAPIFunc.GetRootHash(0xf21dc8618090?, 0x4453b860c0?, 0x420b20cd90?)
        github.com/erigontech/erigon/polygon/bor/bor.go:1302 +0x2c
github.com/erigontech/erigon/polygon/bor/finality.borVerify({0x2f8b650, 0x420b20cd90}, 0x442b6eb2d0, 0x392c2a6, 0x392c5a5, {0x420d682c82, 0x40}, 0x1)
        github.com/erigontech/erigon/polygon/bor/finality/bor_verifier.go:94 +0x178
github.com/erigontech/erigon/polygon/bor/finality.fetchWhitelistCheckpoint({0x2f8b650, 0x420b20cd90}, {0x2fa9348?, 0x442841b810?}, 0x442fd37e80, 0x442b6eb2d0)
        github.com/erigontech/erigon/polygon/bor/finality/whitelist_helpers.go:61 +0x27c
github.com/erigontech/erigon/polygon/bor/finality.handleWhitelistCheckpoint({0x2f8b650?, 0x420b20cd90?}, {0x2fa9348?, 0x442841b810?}, 0x0?)
        github.com/erigontech/erigon/polygon/bor/finality/whitelist.go:182 +0x58
github.com/erigontech/erigon/polygon/bor/finality.retryHeimdallHandler(0x2c5e168, 0x442b6eb2d0, 0x174876e800, 0x6fc23ac00, {0x27447cc, 0x14})
        github.com/erigontech/erigon/polygon/bor/finality/whitelist.go:135 +0x98
github.com/erigontech/erigon/polygon/bor/finality.RetryHeimdallHandler(...)
        github.com/erigontech/erigon/polygon/bor/finality/whitelist.go:117
github.com/erigontech/erigon/polygon/bor/finality.startCheckpointWhitelistService(...)
        github.com/erigontech/erigon/polygon/bor/finality/whitelist.go:82
created by github.com/erigontech/erigon/polygon/bor/finality.Whitelist in goroutine 1
        github.com/erigontech/erigon/polygon/bor/finality/whitelist.go:63 +0x18c
```

**Comment by directsyndikat** [comment]
Update* 
When restarting the server it seems to work.

Situation occurs every time the node is stopped and restarted.

**Comment by AskAlexSharov** [comment]
https://github.com/erigontech/erigon/pull/11389 is not merged yet - can't get it by `git pull`

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/erigontech/erigon/pull/11416

**Comment by AskAlexSharov** [comment]
closing as done. feel free to re-open
