### ISSUE TITLE
blockReader.BlockByNumber() fails after block 19,999,999

### ISSUE THREAD

**Issue by 0xSorcerer** [erigontech/erigon#11429]
When importing erigon in my golang indexer I read directly from the db by doing 

```
var CHAIN_DATA string = "/root/.local/share/erigon/chaindata"
var SNAPSHOT_DATA string = "/root/.local/share/erigon/snapshots"
var ERIGON_DB kv.RwDB
var ERIGON_TX kv.Tx
var BLOCK_READER services.FullBlockReader

func InitializeErigon() {
	ERIGON_DB = mdbx.MustOpen(CHAIN_DATA)
	erigon_tx, err := ERIGON_DB.BeginRo(context.Background())
	if err != nil {
		panic("Error:BeginRo")
	}
	ERIGON_TX = erigon_tx

	allSnapshots := freezeblocks.NewRoSnapshots(ethconfig.BlocksFreezing{}, SNAPSHOT_DATA, 0, log.New())
	allSnapshots.OptimisticReopenWithDB(ERIGON_DB)

	BLOCK_READER = freezeblocks.NewBlockReader(allSnapshots, nil)
}

func CloseErigon() {
	ERIGON_TX.Rollback()
	ERIGON_DB.Close()
}

func GetBlockInfo(blockNumber uint64) {
	block, err := BLOCK_READER.BlockByNumber(context.Background(), ERIGON_TX, blockNumber)

	if err != nil {
		panic("Error: getBlockByNumber")
	}

	println(block.Hash().String())
}
```

This works up to block 19,999,999, then, for later blocks, it gives me the error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x124f865]
```

Why doesn't it work for later blocks?

**Comment by AskAlexSharov** [comment]
Show 50 lines of stack trace

**Comment by 0xSorcerer** [comment]
This is the entire log I get with stack trace

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb0518c]

goroutine 1 [running]:
github.com/ledgerwatch/erigon/core/types.(*Block).Hash(0xc000606fc0?)
        /root/atlas-erigon/erigon/core/types/block.go:1346 +0x2c
main.GetBlockInfo(0xc0000061c0?)
        /root/atlas-erigon/atlas/main.go:124 +0x5e
main.main()
        /root/atlas-erigon/atlas/main.go:418 +0x1d
exit status 2
```

**Comment by AskAlexSharov** [comment]
so, panic is not inside `blockReader` it's in `block.Hash()` call. which means you need add:
```
if block == nil {
    panic("block not found")
}
```
to print "why block not found" log messages you can add 
```
ctx := dbg.ContextWithDebug(context.Background(), true)
BlockByNumber(ctx)
```

**Comment by AskAlexSharov** [comment]
probably your node not synced or you forgot `--internalcl`

**Comment by 0xSorcerer** [comment]
Thanks, the problem was that the `--internalcl`flag was missing.
