### ISSUE TITLE
After using caplin, erigon always encounters painc errors when starting

### ISSUE THREAD

**Issue by rayn316** [erigontech/erigon#11482]
#### System information

Erigon version: v2.60.5

OS & Version: Linux

Commit hash: ea49defcb0de1267dfadb531288466737d839bdb

Erigon Command (with flags/config):

Consensus Layer: caplin

Consensus Layer Command (with flags/config):

Chain/Network: 

#### Steps to reproduce the behaviour
After putting the data of caplin on other nodes into the archive node, it is started, but this error keeps occurring, causing the process to restart

#### Backtrace

````
Aug 05 11:45:11 erigon[3027515]: [INFO] [08-05|11:45:11.570] Full backfilling finished                app=caplin stage=DownloadHistoricalBlocks
Aug 05 11:45:11 erigon[3027515]: [INFO] [08-05|11:45:11.570] Downloading blobs backwards              app=caplin stage=DownloadHistoricalBlocks from=9667041 to=8626176
Aug 05 11:45:11 erigon[3027515]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 05 11:45:11 erigon[3027515]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1787e29]
Aug 05 11:45:11 erigon[3027515]: goroutine 49919 [running]:
Aug 05 11:45:11 erigon[3027515]: github.com/ledgerwatch/erigon/cl/antiquary.(*Antiquary).initializeStateAntiquaryIfNeeded(0xc06ce5a820, {0x3195648, 0xc0842df4a0}, {0x31bac18, 0xc210776cc0})
Aug 05 11:45:11 erigon[3027515]:         github.com/ledgerwatch/erigon/cl/antiquary/state_antiquary.go:451 +0x2c9
Aug 05 11:45:11 erigon[3027515]: github.com/ledgerwatch/erigon/cl/antiquary.(*Antiquary).IncrementBeaconState(0xc06ce5a820, {0x3195648, 0xc0842df4a0}, 0x9381ff)
Aug 05 11:45:11 erigon[3027515]:         github.com/ledgerwatch/erigon/cl/antiquary/state_antiquary.go:120 +0x195
Aug 05 11:45:11 erigon[3027515]: github.com/ledgerwatch/erigon/cl/antiquary.(*Antiquary).loopStates(0xc06ce5a820, {0x3195648, 0xc0842df4a0})
Aug 05 11:45:11 erigon[3027515]:         github.com/ledgerwatch/erigon/cl/antiquary/state_antiquary.go:70 +0x2cc
Aug 05 11:45:11 erigon[3027515]: created by github.com/ledgerwatch/erigon/cl/antiquary.(*Antiquary).Loop in goroutine 48971
Aug 05 11:45:11 erigon[3027515]:         github.com/ledgerwatch/erigon/cl/antiquary/antiquary.go:166 +0x101f
Aug 05 11:45:13 systemd[1]: ethereum-archive.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 05 11:45:13 systemd[1]: ethereum-archive.service: Failed with result 'exit-code'.
Aug 05 11:45:13 systemd[1]: ethereum-archive.service: Consumed 6min 37.207s CPU time.
Aug 05 11:45:18 systemd[1]: ethereum-archive.service: Scheduled restart job, restart counter is at 4.
````

**Comment by Giulio2002** [comment]
is this a fresh sync or did you restart the node?
