### ISSUE TITLE
TestAggregatorV3_PruneSmallBatches sporadically fails CI

### ISSUE THREAD

**Issue by taratorio** [erigontech/erigon#11523]
example: https://github.com/erigontech/erigon/actions/runs/10298448710/job/28503610003?pr=11426

```
--- FAIL: TestAggregatorV3_PruneSmallBatches (1.48s)
    aggregator_test.go:434: step=10 tx_count=50
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x102bd8800]

goroutine 5585 [running]:
testing.tRunner.func1.2({0x1030af900, 0x1035e8f30})
	testing/testing.go:1545 +0x1c4
testing.tRunner.func1()
	testing/testing.go:1548 +0x360
panic({0x1030af900?, 0x1035e8f30?})
	runtime/panic.go:914 +0x218
github.com/erigontech/mdbx-go/mdbx.openCursor.func1(0x14000a69a58?, 0x2d04e2c?, 0x50?)
	github.com/erigontech/mdbx-go@v0.38.4/mdbx/cursor.go:69 +0x20
github.com/erigontech/mdbx-go/mdbx.openCursor(0x0, 0x114090?)
	github.com/erigontech/mdbx-go@v0.38.4/mdbx/cursor.go:69 +0x64
github.com/erigontech/mdbx-go/mdbx.(*Txn).OpenCursor(...)
	github.com/erigontech/mdbx-go@v0.38.4/mdbx/txn.go:661
github.com/erigontech/erigon-lib/kv/mdbx.(*MdbxTx).stdCursor(0x140001134a0, {0x102ee4083, 0x12})
	github.com/erigontech/erigon-lib/kv/mdbx/kv_mdbx.go:1344 +0x108
github.com/erigontech/erigon-lib/kv/mdbx.(*MdbxTx).RwCursorDupSort(0x0?, {0x102ee4083?, 0x14000a69bf8?})
	github.com/erigontech/erigon-lib/kv/mdbx/kv_mdbx.go:1358 +0x20
github.com/erigontech/erigon-lib/kv/mdbx.(*MdbxTx).CursorDupSort(0x1030568c0?, {0x102ee4083?, 0x103865eb8?})
	github.com/erigontech/erigon-lib/kv/mdbx/kv_mdbx.go:1366 +0x20
github.com/erigontech/erigon-lib/state.(*HistoryChangesIterDB).advanceSmallVals(0x140000d6380)
	github.com/erigontech/erigon-lib/state/history.go:1989 +0xbc
github.com/erigontech/erigon-lib/state.(*HistoryChangesIterDB).advance(0x103c50000?)
	github.com/erigontech/erigon-lib/state/history.go:1913 +0x78
github.com/erigontech/erigon-lib/state.(*HistoryRoTx).iterateChangedRecent(0x14003126a00, 0x0, 0x32, 0xf6?, 0x7fffffffffffffff, {0x10318fdf8?, 0x140001134a0})
	github.com/erigontech/erigon-lib/state/history.go:1690 +0x1c8
github.com/erigontech/erigon-lib/state.(*HistoryRoTx).HistoryRange(0x140063224e0?, 0x103187888?, 0x14000242800?, 0x1, 0x0?, {0x10318fdf8, 0x140001134a0})
	github.com/erigontech/erigon-lib/state/history.go:1705 +0xb4
github.com/erigontech/erigon-lib/state.TestAggregatorV3_PruneSmallBatches(0x140063224e0)
	github.com/erigontech/erigon-lib/state/aggregator_test.go:531 +0xab4
testing.tRunner(0x140063224e0, 0x10317e6c8)
	testing/testing.go:1595 +0xe8
created by testing.(*T).Run in goroutine 1
	testing/testing.go:1648 +0x33c
FAIL	github.com/erigontech/erigon-lib/state
```

**Comment by taratorio** [comment]
will re-open if I see it again
