### ISSUE TITLE
dl: nil ptr

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11759]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf68866]

goroutine 147 [running]:
github.com/anacrolix/torrent/metainfo.(*Info).NumPieces(...)
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-35/metainfo/info.go:134
github.com/anacrolix/torrent.(*Torrent).numPieces(0xc01154fc08?, 0x1?)
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-35/torrent.go:1057 +0x86
github.com/anacrolix/torrent.(*Torrent).NumPieces(...)
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-35/t.go:82
github.com/erigontech/erigon-lib/downloader.availableTorrents({0x1cb23d0, 0xc00063b680}, {0xc0fd128008, 0x826, 0x15dba80?}, 0xc0018d7590, 0x80, 0x0)
	/home/ubuntu/erigon/erigon-lib/downloader/downloader.go:1788 +0xfd
github.com/erigontech/erigon-lib/downloader.(*Downloader).mainLoop.func2()
	/home/ubuntu/erigon/erigon-lib/downloader/downloader.go:1133 +0x8a5
created by github.com/erigontech/erigon-lib/downloader.(*Downloader).mainLoop in goroutine 128
	/home/ubuntu/erigon/erigon-lib/downloader/downloader.go:877 +0x21f
exit status 2panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf68866]

goroutine 147 [running]:
github.com/anacrolix/torrent/metainfo.(*Info).NumPieces(...)
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-35/metainfo/info.go:134
github.com/anacrolix/torrent.(*Torrent).numPieces(0xc01154fc08?, 0x1?)
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-35/torrent.go:1057 +0x86
github.com/anacrolix/torrent.(*Torrent).NumPieces(...)
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-35/t.go:82
github.com/erigontech/erigon-lib/downloader.availableTorrents({0x1cb23d0, 0xc00063b680}, {0xc0fd128008, 0x826, 0x15dba80?}, 0xc0018d7590, 0x80, 0x0)
	/home/ubuntu/erigon/erigon-lib/downloader/downloader.go:1788 +0xfd
github.com/erigontech/erigon-lib/downloader.(*Downloader).mainLoop.func2()
	/home/ubuntu/erigon/erigon-lib/downloader/downloader.go:1133 +0x8a5
created by github.com/erigontech/erigon-lib/downloader.(*Downloader).mainLoop in goroutine 128
	/home/ubuntu/erigon/erigon-lib/downloader/downloader.go:877 +0x21f
exit status 2
```

**Comment by hitdavid** [comment]
got this too,
Build info                               git_branch=main git_tag=v3.0.0-alpha2-156-g7cb7f1dbfc git_commit=7cb7f1dbfc60f88be17f0a1ee3e33ca20d875876

```
panic: runtime error: invalid memory address or nil pointer dereference                                           
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf82ca6]                                           

goroutine 6782 [running]:                                
github.com/anacrolix/torrent/metainfo.(*Info).NumPieces(...)                                                      
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/metainfo/info.go:134                                                                                                                                     
github.com/anacrolix/torrent.(*Torrent).numPieces(0xc262b37808?, 0x1?)                                            
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/torrent.go:1057 +0x86                                                                                                                                    
github.com/anacrolix/torrent.(*Torrent).NumPieces(...)                                                            
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/t.go:82                                
github.com/erigontech/erigon-lib/downloader.availableTorrents({0x32501c0, 0xc0d4954cd0}, {0x0, 0x0, 0x2499780?}, 0xc1b359eea0, 0x80, 0x840)                                                                                         
        github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/downloader/downloader.go:1788 +0xfd                                                                                                                     
github.com/erigontech/erigon-lib/downloader.(*Downloader).mainLoop.func2()                                        
        github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/downloader/downloader.go:1133 +0x8a5                                                                                                                    
created by github.com/erigontech/erigon-lib/downloader.(*Downloader).mainLoop in goroutine 6886                                                                                                                                     
        github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/downloader/downloader.go:877 +0x21f
```

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/erigontech/erigon/pull/11769
