### ISSUE TITLE
[signal SIGSEGV: segmentation violation code=0x1 addr=... pc=...]

### ISSUE THREAD

**Issue by nining** [erigontech/erigon#12035]
#### System information

Erigon version: erigon version 2.60.8-dec9d206

OS & Version: Linux Ubuntu 24.01.1 LTS

Commit hash: dec9d206

Erigon Command (with flags/config): erigon --chain mainnet --private.api.addr="" --http.addr 0.0.0.0 --http.vhosts "*" --http.api=eth,erigon,web3,net,debug,trace,txpool--http.corsdomain "*" --authrpc.addr=0.0.0.0 --authrpc.vhosts "*"  --ws --maxpeers 200 --rpc.batch.limit 100000 --rpc.returndata.limit 10000000 --rpc.batch.concurrency 100000 --bodies.cache 65536M --state.cache 16384M --db.pagesize=16kb --rpc.gascap=500000000 --torrent.download.rate=1000mb

Consensus Layer:

lighthouse

Chain/Network:  mainnet

#### Expected behaviour

start normally as usual

#### Actual behaviour

crashed

#### Steps to reproduce the behaviour

everytime

#### Backtrace

````
mdbx_setup_dxb:16114 opening after an unclean shutdown, but boot-id(b6e9f0aec954ca5f-623d47ecb55d443a) is MATCH: rollback NOT needed, steady-sync NEEDED
mdbx_setup_dxb:16114 opening after an unclean shutdown, but boot-id(b6e9f0aec954ca5f-623d47ecb55d443a) is MATCH: rollback NOT needed, steady-sync NEEDED
[INFO] [09-19|12:10:55.156] [1/12 Snapshots] Requesting downloads 
[INFO] [09-19|12:10:59.426] [snapshots:download] Stat                blocks=19160k indices=19140k alloc=4.0GB sys=4.5GB
[INFO] [09-19|12:10:59.426] [snapshots:missed-idx] Stat              blocks=19160k indices=19140k alloc=4.0GB sys=4.5GB
unexpected fault address 0x642d22960fc1
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x642d22960fc1 pc=0xab844f]

goroutine 5402 [running]:
runtime.throw({0x28ed786?, 0xc065594f20?})
	runtime/panic.go:1077 +0x5c fp=0xc0a9970e18 sp=0xc0a9970de8 pc=0x460cfc
runtime.sigpanic()
	runtime/signal_unix.go:875 +0x285 fp=0xc0a9970e78 sp=0xc0a9970e18 pc=0x477fa5
github.com/ledgerwatch/erigon-lib/recsplit.(*GolombRiceReader).ReadReset(...)
	github.com/ledgerwatch/erigon-lib@v1.0.0/recsplit/golomb_rice.go:94
github.com/ledgerwatch/erigon-lib/recsplit.(*Index).Lookup(0xc0a9d14a00, 0xa790c4b1759876e, 0x8abe05abde7b7bd6)
	github.com/ledgerwatch/erigon-lib@v1.0.0/recsplit/index.go:296 +0x12f fp=0xc0a9970f30 sp=0xc0a9970e78 pc=0xab844f
github.com/ledgerwatch/erigon-lib/recsplit.(*IndexReader).Lookup(0xc0f16088a0, {0xc065594f20?, 0x1?, 0x1?})
	github.com/ledgerwatch/erigon-lib@v1.0.0/recsplit/index_reader.go:61 +0x39 fp=0xc0a9970f60 sp=0xc0a9970f30 pc=0xab9819
github.com/ledgerwatch/erigon/turbo/snapshotsync/freezeblocks.(*BlockReader).txnByHash(0x704accecfb28?, {0x91, 0x69, 0xa9, 0x3f, 0x9f, 0x91, 0xcf, 0xb7, 0xa2, ...}, ...)
	github.com/ledgerwatch/erigon/turbo/snapshotsync/freezeblocks/block_reader.go:947 +0x245 fp=0xc0a9971138 sp=0xc0a9970f60 pc=0x1728ea5
github.com/ledgerwatch/erigon/turbo/snapshotsync/freezeblocks.(*BlockReader).TxnLookup(0xc0a3957270, {0x40?, 0x0?}, {0x704accecfb28?, 0xc03fe91080?}, {0x91, 0x69, 0xa9, 0x3f, 0x9f, ...})
	github.com/ledgerwatch/erigon/turbo/snapshotsync/freezeblocks/block_reader.go:1039 +0xe8 fp=0xc0a99711c8 sp=0xc0a9971138 pc=0x17298c8
github.com/ledgerwatch/erigon/turbo/jsonrpc.(*BaseAPI).txnLookup(...)
	github.com/ledgerwatch/erigon/turbo/jsonrpc/eth_api.go:181
github.com/ledgerwatch/erigon/turbo/jsonrpc.(*APIImpl).GetTransactionByHash(0xc0a9e44bd0, {0x3166e08, 0xc0eafca320}, {0x91, 0x69, 0xa9, 0x3f, 0x9f, 0x91, 0xcf, ...})
	github.com/ledgerwatch/erigon/turbo/jsonrpc/eth_txs.go:36 +0x1a5 fp=0xc0a9971400 sp=0xc0a99711c8 pc=0x1e1e9c5
runtime.call64(0xc11352d830, 0xc0a3d1ac88, 0xc065594ee0, 0x20, 0x20, 0x38, 0xc0a9971980)
	runtime/asm_amd64.s:749 +0x43 fp=0xc0a9971450 sp=0xc0a9971400 pc=0x495d43
runtime.reflectcall(0x275ee60?, 0xc065594ec0?, 0x4?, 0x29c0f93?, 0x0?, 0x12?, 0x275ee60?)
	<autogenerated>:1 +0x36 fp=0xc0a9971490 sp=0xc0a9971450 pc=0x49a176
reflect.Value.call({0xc0b421e660?, 0xc0a3d1ac88?, 0x704a62038538?}, {0x28eafc2, 0x4}, {0xc0eafca370, 0x3, 0x43c3b2?})
	reflect/value.go:596 +0xce7 fp=0xc0a9971aa0 sp=0xc0a9971490 pc=0x4cd507
reflect.Value.Call({0xc0b421e660?, 0xc0a3d1ac88?, 0xc0af2362a8?}, {0xc0eafca370?, 0xc065594ec0?, 0x27b5a00?})
	reflect/value.go:380 +0xb9 fp=0xc0a9971b18 sp=0xc0a9971aa0 pc=0x4cc5d9
github.com/ledgerwatch/erigon/rpc.(*callback).call(0xc000b33880, {0x3166e08?, 0xc0eafca320}, {0xc0f160e0a8, 0x18}, {0xc080086060, 0x1, 0x24c0780?}, 0xc0b4043b60)
	github.com/ledgerwatch/erigon/rpc/service.go:224 +0x4aa fp=0xc0a9971c70 sp=0xc0a9971b18 pc=0x111c2ea
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc0ff89a500?, {0x3166e08?, 0xc0eafca320?}, 0xc0eafd81c0, 0x1?, {0xc080086060?, 0x0?, 0xc114526d68?}, 0x442e76?)
	github.com/ledgerwatch/erigon/rpc/handler.go:532 +0x1ff fp=0xc0a9971d18 sp=0xc0a9971c70 pc=0x1114eff
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc0aa61a5b0, 0xc1b21a69c0, 0xc0eafd81c0, 0xc002680800?)
	github.com/ledgerwatch/erigon/rpc/handler.go:482 +0x2fc fp=0xc0a9971dd8 sp=0xc0a9971d18 pc=0x11144bc
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc0aa61a5b0, 0xc1b21a69c0?, 0xc0eafd81c0, 0x28?)
	github.com/ledgerwatch/erigon/rpc/handler.go:421 +0x551 fp=0xc0a9971ee0 sp=0xc0a9971dd8 pc=0x11132f1
github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1(0xc1b21a69c0)
	github.com/ledgerwatch/erigon/rpc/handler.go:241 +0x165 fp=0xc0a9971f78 sp=0xc0a9971ee0 pc=0x1111b05
github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1()
	github.com/ledgerwatch/erigon/rpc/handler.go:334 +0xbe fp=0xc0a9971fe0 sp=0xc0a9971f78 pc=0x111251e
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc0a9971fe8 sp=0xc0a9971fe0 pc=0x4976a1
created by github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc in goroutine 5338
	github.com/ledgerwatch/erigon/rpc/handler.go:330 +0x79

goroutine 1 [chan receive]:
runtime.gopark(0xc008007760?, 0x46bf8b?, 0x40?, 0x77?, 0x46bfc0?)
	runtime/proc.go:398 +0xce fp=0xc0b604b728 sp=0xc0b604b708 pc=0x463c8e
runtime.chanrecv(0xc0011a40c0, 0x0, 0x1)
	runtime/chan.go:583 +0x3cd fp=0xc0b604b7a0 sp=0xc0b604b728 pc=0x42f04d
runtime.chanrecv1(0xc000670000?, 0x317aa40?)
	runtime/chan.go:442 +0x12 fp=0xc0b604b7c8 sp=0xc0b604b7a0 pc=0x42ec52
github.com/ledgerwatch/erigon/node.(*Node).Wait(...)
	github.com/ledgerwatch/erigon/node/node.go:272
github.com/ledgerwatch/erigon/turbo/node.(*ErigonNode).Serve(0xc0a9e5ad40)
	github.com/ledgerwatch/erigon/turbo/node/node.go:34 +0x6e fp=0xc0b604b818 sp=0xc0b604b7c8 pc=0x21cb2ee
main.runErigon(0xc0011956c0)

````

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/erigontech/erigon/pull/12373
