### ISSUE TITLE
Deadlock while syncing e3

### ISSUE THREAD

**Issue by yperbasis** [erigontech/erigon#12664]
#### System information

OS & Version: Ubuntu

Commit hash: 063147285ea282451d9098bcf14275f735042c68

Erigon Command (with flags/config):
```
erigon --datadir /mnt/giant/erigon3/ethereum --http.api=eth,debug,net,trace,web3,erigon
```

Consensus Layer: none

Chain/Network: mainnet

#### Actual behaviour
```
Deadlock detected goroutine 18169 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x5e
github.com/erigontech/erigon/cl/beacon/synced_data.(*SyncedDataManager).HeadState(0xc005c4e320)
        github.com/erigontech/erigon/cl/beacon/synced_data/synced_data.go:91 +0x9a
github.com/erigontech/erigon/cl/phase1/network/services.(*aggregateAndProofServiceImpl).ProcessMessage(0xc02e28c48
0, {0x1f7?, 0x1f7?}, 0x4?, 0xc16e767428)
        github.com/erigontech/erigon/cl/phase1/network/services/aggregate_and_proof_service.go:101 +0x45
github.com/erigontech/erigon/cl/phase1/network.(*GossipManager).routeAndProcess(0xc01c6b60e0, {0x3332e38, 0xc00587
1310}, 0xc0b308d620)
        github.com/erigontech/erigon/cl/phase1/network/gossip_manager.go:241 +0xc38
github.com/erigontech/erigon/cl/phase1/network.(*GossipManager).onRecv(0xc01c6b60e0, {0x3332e38, 0xc005871310}, 0x
c267acbce0, 0xc01d571e20?)
        github.com/erigontech/erigon/cl/phase1/network/gossip_manager.go:142 +0x14c
github.com/erigontech/erigon/cl/phase1/network.(*GossipManager).Start.func1.1()
        github.com/erigontech/erigon/cl/phase1/network/gossip_manager.go:302 +0x13b
created by github.com/erigontech/erigon/cl/phase1/network.(*GossipManager).Start.func1 in goroutine 18101
        github.com/erigontech/erigon/cl/phase1/network/gossip_manager.go:309 +0xb4

Deadlock detected goroutine 18098 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x5e
github.com/erigontech/erigon/cl/beacon/synced_data.(*SyncedDataManager).HeadState(0xc005c4e320)
        github.com/erigontech/erigon/cl/beacon/synced_data/synced_data.go:91 +0x9a
github.com/erigontech/erigon/cl/phase1/network/services.(*aggregateAndProofServiceImpl).ProcessMessage(0xc02e28c480, {0x2b0d2b3?, 0x57a74c0?}, 0x5?, 0xc34937eea0)
        github.com/erigontech/erigon/cl/phase1/network/services/aggregate_and_proof_service.go:101 +0x45
github.com/erigontech/erigon/cl/phase1/network/services.(*aggregateAndProofServiceImpl).loop.func1({0x25810e0, 0xc22d91cd40}, {0x24e6c00?, 0xc5549d0620})
        github.com/erigontech/erigon/cl/phase1/network/services/aggregate_and_proof_service.go:392 +0x205
sync.(*Map).Range(0xc13a181f50?, 0xc13a181f80)
        sync/map.go:501 +0x1f8
github.com/erigontech/erigon/cl/phase1/network/services.(*aggregateAndProofServiceImpl).loop(0xc02e28c480, {0x3332e38, 0xc005871310})
        github.com/erigontech/erigon/cl/phase1/network/services/aggregate_and_proof_service.go:376 +0xc5
created by github.com/erigontech/erigon/cl/phase1/network/services.NewAggregateAndProofService in goroutine 197
        github.com/erigontech/erigon/cl/phase1/network/services/aggregate_and_proof_service.go:92 +0x1b5
```

Full log:
[out_ethereum.log](https://github.com/user-attachments/files/17661260/out_ethereum.log)

**Comment by yperbasis** [comment]
Apparently fixed by @Giulio2002 already
