### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by 0x19** [erigontech/erigon#13040]
#### System information

Erigon version: `./erigon --version`

erigon version 2.59.3-088fd8ef

OS & Version:  

```
cat /etc/os-release
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
```

Kernel `6.5.0-44-generic`

Commit hash:  088fd8ef69389a72da6faa0fc7903a4ba5726911 (HEAD, tag: v2.59.3)

Erigon Command (with flags/config):

```
sudo /.../erigon/build/bin/erigon   --config /.../nodes/erigon/config.yaml 
```

```
datadir : '...'
chain : "mainnet"
http : true
graphql: true
ws: true
private.api.addr : "localhost:9090"
internalcl: true
http.api : ["eth", "admin", "erigon","web3","net","debug","trace","txpool", "ots"]
http.corsdomain: "*"
torrent.download.rate: 100mb
torrent.upload.rate: 1mb
maxpeers: 300
rpc.batch.concurrency: 1500
rpc.batch.limit: 1500
verbosity: "info"
log.console.verbosity: "info"
sync.loop.prune.limit: 2
```

Chain/Network: 

ethereum mainnet

#### Expected behaviour

Erigon not crashing.

#### Actual behaviour
```
INFO[12-08|13:56:40.833] [updateForkchoice] Fork choice update: flushing in-memory state (built by previous newPayload) 
INFO[12-08|13:56:41.345] RPC Daemon notified of new headers       from=21357911 to=21357912 amount=1 hash=0x01551471931fa9d2ed12c974b1b2c2c6fedaf6cc8a33fc0feb6397a2a8b6a867 header sending=24.031µs log sending=710ns
INFO[12-08|13:56:41.345] head updated                             hash=0x01551471931fa9d2ed12c974b1b2c2c6fedaf6cc8a33fc0feb6397a2a8b6a867 number=21357912
panic: runtime error: integer divide by zero

goroutine 20171402 [running]:
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.processRewardsAndPenaltiesPostAltair({0x31bb938, 0xc1b82e62a0}, {0xc334254000, 0x105b8b, 0xc031631900?}, {0xc182285810, 0x3, 0x3})
	github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_rewards_and_penalties.go:46 +0x717
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.ProcessRewardsAndPenalties({0x31bb938?, 0xc1b82e62a0}, {0xc334254000, 0x105b8b, 0x19e501}, {0xc182285810, 0x3, 0x3})
	github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_rewards_and_penalties.go:230 +0x111
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.ProcessEpoch({0x31bb938, 0xc1b82e62a0})
	github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_epoch.go:47 +0x1dc
github.com/ledgerwatch/erigon/cl/transition/impl/eth2.(*impl).ProcessSlots(0xc0001b2180?, {0x31bb938, 0xc1b82e62a0}, 0xa14880)
	github.com/ledgerwatch/erigon/cl/transition/impl/eth2/operations.go:844 +0x19a
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).getCheckpointState(0xc0a14b8000, {0xc0dd8c715c, 0x28, 0x88})
	github.com/ledgerwatch/erigon/cl/phase1/forkchoice/utils.go:128 +0x21d
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).OnAttestation(0xc0a14b8000, 0xc0dd8c7100, 0x1, 0x0)
	github.com/ledgerwatch/erigon/cl/phase1/forkchoice/on_attestation.go:48 +0x2c5
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func8.3.1(0xc058394100?, 0xc1593de240?, 0xc18bc80138?)
	github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:669 +0x6b
github.com/ledgerwatch/erigon/cl/cltypes/solid.(*ListSSZ[...]).Range(0x195, 0xc08b087fb8?)
	github.com/ledgerwatch/erigon/cl/cltypes/solid/list_ssz.go:142 +0x72
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func8.3()
	github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:666 +0x68
created by github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func8
	github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:665 +0x187b
```

#### Steps to reproduce the behaviour

I have no idea, just start the erigon and hope it happens. Saw it for the first time now.

**Comment by AskAlexSharov** [comment]
upgrade

**Comment by Giulio2002** [comment]
Hi, so this is caplin which is going to be deprecated on Erigon 2.0, so it will not be fixed on the stable branch

**Comment by 0x19** [comment]
Thanks! I've upgraded to 2.60.10 - works w/o issues.
