### ISSUE TITLE
release/2.61: panic in clean-exit-block-downloading test

### ISSUE THREAD

**Issue by yperbasis** [erigontech/erigon#13193]
There is a panic in this run https://github.com/erigontech/erigon/actions/runs/12419039690/job/34673503099 of the clean-exit-block-downloding test:
```
!!->panic: runtime error: index out of range [2] with length 2
OK->
OK->goroutine 358 [running]:
OK->github.com/erigontech/erigon-lib/chain/snapcfg.Preverified.Versioned({0xc000b96000?, 0xc000c7e270?, 0x298713d?}, 0x1, 0x1, {0x0, 0x0, 0xc0c040b640?})
OK->github.com/erigontech/erigon-lib@v1.0.0/chain/snapcfg/util.go:156 +0x4a9
OK->github.com/erigontech/erigon-lib/chain/snapcfg.VersionedCfg({0x298713d, 0x7}, 0x1, 0x1)
OK->github.com/erigontech/erigon-lib@v1.0.0/chain/snapcfg/util.go:451 +0x85
OK->github.com/erigontech/erigon-lib/downloader.initSnapshotLock.func1.1(0xc0013d9710?, 0xc0c02d4150, {0x1, 0x1406f40, 0x141f5e0, {0xc0aed14b66, 0x21}, {0xc0c08122d0, 0x47}, {0xc0aed14b83, ...}, ...}, ...)
OK->github.com/erigontech/erigon-lib@v1.0.0/downloader/downloader.go:586 +0xc8
OK->github.com/erigontech/erigon-lib/downloader.initSnapshotLock.func1()
OK->github.com/erigontech/erigon-lib@v1.0.0/downloader/downloader.go:591 +0x490
OK->golang.org/x/sync/errgroup.(*Group).Go.func1()
OK->golang.org/x/sync@v0.10.0/errgroup/errgroup.go:78 +0x56
OK->created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
OK->golang.org/x/sync@v0.10.0/errgroup/errgroup.go:75 +0x96
*** - 2024-12-20 08:51:10 - Check failed: panic
```
it seems to have started here: https://github.com/erigontech/erigon/commit/0b87495e97f3d3ed266df8206e16a819b28c6b3c
could it be due to the fact that we are starting Erigon on a database made with v2.60.1?

**Comment by AskAlexSharov** [comment]
I think it can't parse E3 file name. Added hot-fix: https://github.com/erigontech/erigon/pull/13196

**Comment by somnathb1** [comment]
For now i was able to rollback the `erigon-snapshot` lib dependency to an older snapshot (which was there in `release/2.61` before the renaming PR) and restart my local instances without any issues. Further, I wasn't able to reproduce this issue directly. It is possible that there was a data corruption in the QA runner server's data.

**Comment by yperbasis** [comment]
`clean-exit-block-downloading` is passing fine in `release/2.61` now.
