### ISSUE TITLE
panic during reading beacon state from cache

### ISSUE THREAD

**Issue by awskii** [erigontech/erigon#13204]
#13181
```
[INFO] [12-20|19:14:12.494] [4/6 Execution]                          blk=4287854 blks=2575 blk/s=129.2 txs=245258 tx/s=12.30k gas/s=619.63M buf=1006.9MB/512.0MB stepsInDB=1.15 step=43.4 in
Mem=false alloc=9.3GB sys=18.6GB
[INFO] [12-20|19:14:26.615] P2P                                      app=caplin peers=28
[INFO] [12-20|19:14:49.856] Committed                                time=37.36230641s block=4287854 txNum=67791963 step=43.4 flush+commitment=35.351356984s tx.commit=2.010107877s prune=68
5.315µs
[INFO] [12-20|19:14:49.869] [4/6 Execution]                          blk=4287855 blks=2 blk/s=0.1 txs=128 tx/s=3 gas/s=179.15k buf=84.4KB/512.0MB stepsInDB=1.39 step=43.4 inMem=false alloc
=7.8GB sys=18.6GB
[INFO] [12-20|19:14:52.595] [4/6 Execution]                          blk=4288128 blks=274 blk/s=100.5 txs=29433 tx/s=10.79k gas/s=559.27M buf=146.4MB/512.0MB stepsInDB=1.39 step=43.4 inMem
=false alloc=9.5GB sys=18.6GB
[INFO] [12-20|19:15:12.434] [p2p] GoodPeers                          eth68=31 eth67=32
[INFO] [12-20|19:15:12.437] [txpool] stat                            pending=0 baseFee=0 queued=264 alloc=10.4GB sys=18.6GB
[INFO] [12-20|19:15:12.516] [4/6 Execution]                          blk=4290336 blks=2209 blk/s=110.9 txs=228105 tx/s=11.45k gas/s=573.97M buf=779.2MB/512.0MB stepsInDB=1.39 step=43.6 inM
em=false alloc=10.4GB sys=18.6GB
[INFO] [12-20|19:15:13.894] [mem] memory stats                       Rss=55.8GB Size=0B Pss=55.8GB SharedClean=2.5MB SharedDirty=0B PrivateClean=41.6GB PrivateDirty=14.2GB Referenced=37.0G
B Anonymous=14.2GB Swap=0B alloc=10.5GB sys=18.6GB
[INFO] [12-20|19:15:26.615] P2P                                      app=caplin peers=31
[INFO] [12-20|19:15:42.107] [Caplin] Forward Sync                    app=caplin stage=ForwardSync from=10658048 to=10658176
[INFO] [12-20|19:16:13.895] [Caplin] Forward Sync                    app=caplin stage=ForwardSync progress=10658121 distance-from-chain-tip=11m0s estimated-time-remaining=22s
[INFO] [12-20|19:16:26.615] P2P                                      app=caplin peers=14
panic: runtime error: makeslice: len out of range

goroutine 8052714 [running]:
github.com/erigontech/erigon/cl/phase1/core/state.(*CachingBeaconState).decodeActiveValidatorsCache(0xc0b56a5920, {0x3409080, 0xc0f519ae40}, {0xc1b5933790, 0x8, 0x8})
        github.com/erigontech/erigon/cl/phase1/core/state/cache.go:495 +0x27a
github.com/erigontech/erigon/cl/phase1/core/state.(*CachingBeaconState).DecodeCaches(0xc0b56a5920, {0x3409080, 0xc0f519ae40})
        github.com/erigontech/erigon/cl/phase1/core/state/cache.go:358 +0x6b
github.com/erigontech/erigon/cl/phase1/forkchoice/fork_graph.(*forkGraphDisk).readBeaconStateFromDisk(0xc0c2bb0288, {0xe3, 0x37, 0x60, 0xf4, 0x8d, 0x67, 0xe9, 0x30, 0x3, ...}, ...)
        github.com/erigontech/erigon/cl/phase1/forkchoice/fork_graph/fork_graph_disk_fs.go:102 +0xb71
github.com/erigontech/erigon/cl/phase1/forkchoice/fork_graph.(*forkGraphDisk).getState(0xc0c2bb0288, {0xe3, 0x37, 0x60, 0xf4, 0x8d, 0x67, 0xe9, 0x30, 0x3, ...}, ...)
        github.com/erigontech/erigon/cl/phase1/forkchoice/fork_graph/fork_graph_disk.go:381 +0x23e
github.com/erigontech/erigon/cl/phase1/forkchoice/fork_graph.(*forkGraphDisk).GetState(0xc0070e1da0?, {0xe3, 0x37, 0x60, 0xf4, 0x8d, 0x67, 0xe9, 0x30, 0x3, ...}, ...)
        github.com/erigontech/erigon/cl/phase1/forkchoice/fork_graph/fork_graph_disk.go:339 +0x28
github.com/erigontech/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).GetStateAtBlockRoot(0xc125936120?, {0xe3, 0x37, 0x60, 0xf4, 0x8d, 0x67, 0xe9, 0x30, 0x3, ...}, ...)
        github.com/erigontech/erigon/cl/phase1/forkchoice/forkchoice.go:361 +0xd7
github.com/erigontech/erigon/cl/phase1/stages.processDownloadedBlockBatches({0x3429b78, 0xc09733edc0}, 0xc0ac1d2b40, 0xa2a17c, 0x1, {0xc107555200, 0xb, 0x10})
        github.com/erigontech/erigon/cl/phase1/stages/forward_sync.go:127 +0x3cc
github.com/erigontech/erigon/cl/phase1/stages.forwardSync.func1(0xa2a17c, {0xc107555200, 0xb, 0x10})
        github.com/erigontech/erigon/cl/phase1/stages/forward_sync.go:181 +0x91
github.com/erigontech/erigon/cl/phase1/network.(*ForwardBeaconDownloader).RequestMore(0xc17186de30, {0x3429b78, 0xc09733edc0})
        github.com/erigontech/erigon/cl/phase1/network/beacon_downloader.go:125 +0x472
github.com/erigontech/erigon/cl/phase1/stages.forwardSync({0x3429b78, 0xc09733edc0}, {0x3440448, 0xc1718515a0}, 0xc0ac1d2b40, {0x1c, 0x5150b, 0x5150a, 0xa2a180, 0xa2a141, ...})
        github.com/erigontech/erigon/cl/phase1/stages/forward_sync.go:213 +0x454
github.com/erigontech/erigon/cl/clstages.(*StageGraph[...]).StartWithStage.func1()
        github.com/erigontech/erigon/cl/clstages/clstages.go:54 +0x6e
created by github.com/erigontech/erigon/cl/clstages.(*StageGraph[...]).StartWithStage in goroutine 421
        github.com/erigontech/erigon/cl/clstages/clstages.go:50 +0x3a5
```

**Comment by errge** [comment]
Sorry, but I duplicated this in #13217 , because I didn't notice this ticket in time.

#13217 contains a curl query that can reproduce the issue, if somebody wants to work on this.
