### ISSUE TITLE
merge: not found file `v1-accounts.140-141.efi`

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#13206]
while worked on gnosis re-sync 
4 days old main
```
[INFO] [12-20|16:44:44.970] Committed                                time=1m19.024941287s block=31357993 txNum=223437663 step=143.0 flush+commitment=1m17.83295875s tx.commit=1.191560217s prune=54.383µs
[INFO] [12-20|16:44:44.991] [4/6 Execution]                          blk=31357994 blks=2 blk/s=0.0 txs=375 tx/s=4 gas/s=139.34k buf=32.7KB/512.0MB stepsInDB=2.00 step=143.0 inMem=false alloc=6.1GB sys=12.9GB
[INFO] [12-20|16:44:56.797] [4/6 Execution]                          blk=31359429 blks=1436 blk/s=121.6 txs=473406 tx/s=40.10k gas/s=1.03B buf=5.6MB/512.0MB stepsInDB=2.00 step=143.3 inMem=false alloc=5.3GB sys=12.9GB
[INFO] [12-20|16:45:14.923] P2P                                      app=caplin peers=19
[INFO] [12-20|16:45:16.802] [4/6 Execution]                          blk=31362014 blks=2586 blk/s=129.3 txs=879301 tx/s=43.95k gas/s=1.10B buf=11.8MB/512.0MB stepsInDB=2.00 step=143.9 inMem=false alloc=6.2GB sys=12.9GB
[INFO] [12-20|16:45:18.725] [snapshots] aggregated                   step=141 took=15m33.38061943s
panic: History.staticFilesInRange: required file not found: v1-accounts.140-141.efi

goroutine 2200478 [running]:
github.com/erigontech/erigon-lib/state.(*DomainRoTx).staticFilesInRange(0xc14beef200, {0x0, {0x1, 0xd09dc30, 0xd398b38}, {{0x1, 0xd09dc30, 0xd398b38}, {0x1, 0xd09dc30, ...}}, ...})
	github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/state/merge.go:246 +0x2b1
github.com/erigontech/erigon-lib/state.(*AggregatorRoTx).staticFilesInRange(_, {{{0x0, {0x1, 0xd09dc30, 0xd398b38}, {{...}, {...}}, 0x17d784}, {0x1, {0x1, ...}, ...}, ...}, ...})
	github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/state/aggregator_files.go:58 +0x19b
github.com/erigontech/erigon-lib/state.(*Aggregator).mergeLoopStep(0xc0019346c8, {0x3409e68, 0xc001a89a40}, 0xd398b38)
	github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/state/aggregator.go:811 +0x58c
github.com/erigontech/erigon-lib/state.(*Aggregator).MergeLoop(0xc0019346c8, {0x3409e68, 0xc001a89a40})
	github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/state/aggregator.go:841 +0x3a
github.com/erigontech/erigon-lib/state.(*Aggregator).BuildFilesInBackground.func1.1()
	github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/state/aggregator.go:1722 +0xdc
created by github.com/erigontech/erigon-lib/state.(*Aggregator).BuildFilesInBackground.func1 in goroutine 1809759
	github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/state/aggregator.go:1715 +0x66e
```

**Comment by AskAlexSharov** [comment]
it was my manual mistake
