### ISSUE TITLE
3.0.0-alpha7 git head crash

### ISSUE THREAD

**Issue by errge** [erigontech/erigon#13288]
#### System information

Erigon version: 3.00.0-alpha7-282c8a67

OS & Version: Linux

Commit hash: 282c8a67

Erigon Command (with flags/config):

```
../../bin/erigon/erigon 
    --datadir ./data \
    --prune.mode archive \
    --http.api=eth,erigon,web3,net,debug,trace,txpool \
    --txpool.pricebump 0 \
    --caplin.archive \
    --diagnostics.disabled \
    --nat none \
    --private.api.addr "" \
    --beacon.api beacon,builder,config,debug,events,node,validator,lighthouse \
    --beacon.api.port 3500 \
    --http.port 8545 \
    --ws --ws.port 8546 \
    --authrpc.port 8551 \
    --torrent.port 20202 --port 30303 --p2p.protocol 68 --p2p.allowed-ports 30303 \
    --caplin.discovery.tcpport 40404 --caplin.discovery.port 40404 --sentinel.port 50505 \
    --rpc.batch.limit 50000 --db.read.concurrency 8 --rpc.returndata.limit 100000000000
```

Consensus Layer: caplin

Consensus Layer Command (with flags/config): builtin

Chain/Network: mainnet

#### Expected behaviour

no crash

#### Actual behaviour

crash

#### Steps to reproduce the behaviour

not sure, was just running it, not actively doing anything on the chain, maybe something on my system sent queries

#### Backtrace

````
panic: assert: missed arguments

goroutine 26366 [running]:
github.com/erigontech/erigon-lib/state.(*AggregatorRoTx).TxNumsInFiles(...)
        github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/state/aggregator.go:935
github.com/erigontech/erigon-lib/state.(*AggregatorRoTx).StepsInFiles(...)
        github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/state/aggregator.go:926
github.com/erigontech/erigon-lib/state.(*AggregatorRoTx).PruneSmallBatches(0xc15ebff920, {0x3457298, 0xc001248500}, 0x274a48a78000, {0x348b480, 0xc16dc3d6c0})
        github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/state/aggregator.go:1153 +0xc30
github.com/erigontech/erigon/eth/stagedsync.PruneExecutionStage(_, {_, _}, {{0x346f370, 0xc0008c0660}, 0x20000000, {0x1, {0x345cd00, 0xc001acd430}, {0x345cd00, ...}, ...}, ...}, ...)
        github.com/erigontech/erigon/eth/stagedsync/stage_execute.go:431 +0x3a5
github.com/erigontech/erigon/eth/stagedsync.PipelineStages.func12(0xc158bf66e0?, {0x0?, 0x0?}, {0x346dd08?, 0xc000a2e240?})
        github.com/erigontech/erigon/eth/stagedsync/default_stages.go:244 +0x7e
github.com/erigontech/erigon/eth/stagedsync.(*Sync).pruneStage(0xc158bf66e0, 0x1, 0xc158ba7810, {0x346f370, 0xc0008c0660}, {0x0, 0x0})
        github.com/erigontech/erigon/eth/stagedsync/sync.go:593 +0x1e6
github.com/erigontech/erigon/eth/stagedsync.(*Sync).RunPrune(0xc158bf66e0, {0x346f370, 0xc0008c0660}, {0x0, 0x0}, 0x1)
        github.com/erigontech/erigon/eth/stagedsync/sync.go:462 +0x8b
github.com/erigontech/erigon/turbo/stages.ProcessFrozenBlocks({0x3457298, 0xc001248500}, {0x346f370, 0xc0008c0660}, {0x3495b48, 0xc001b83d40}, 0xc158bf66e0, 0x0)
        github.com/erigontech/erigon/turbo/stages/stageloop.go:169 +0x230
github.com/erigontech/erigon/turbo/execution/eth1.(*EthereumExecutionModule).Start(0xc146ddbcc0, {0x3457298, 0xc001248500})
        github.com/erigontech/erigon/turbo/execution/eth1/ethereum_execution.go:317 +0x165
created by github.com/erigontech/erigon/eth.(*Ethereum).Start in goroutine 1
        github.com/erigontech/erigon/eth/backend.go:1545 +0xf1f
````

**Comment by Giulio2002** [comment]
try restarting
