### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by Snawoot** [erigontech/erigon#8781]
#### System information

Erigon version: `2.51.0-a0160bee`

OS & Version: Linux

Commit hash: `a0160beee4032491501d89c5347bb1c4710ee6cc`

Erigon Command (with flags/config): 

```
/usr/local/bin/erigon --datadir=/data/polygon/erigon \
        --db.size.limit 8246651162368 \
        --maxpeers=300 \
        --chain=bor-mainnet \
        --http.addr=0.0.0.0 \
        --bodies.cache=21474836480 \
        '--http.vhosts=*' \
        --http.port=8545
```

Consensus Layer: heimdall

Consensus Layer Command (with flags/config):

```
/usr/bin/heimdalld start --home "/data/polygon/heimdall" \
    --chain=mainnet \
    --rest-server
```

Chain/Network: `bor-mainnet` (Polygon Mainnet)

#### Expected behaviour

Don't panic, proceed to work

#### Actual behaviour

Panics, can't proceed to work

#### Steps to reproduce the behaviour

1. Ran erigon @ polygon mainnet

#### Backtrace

````
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xee51cc]
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]: goroutine 11392 [running]:
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]: github.com/ledgerwatch/erigon/core/types.(*Block).Hash(0xc1118b6ea0?)
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]:         github.com/ledgerwatch/erigon/core/types/block.go:1669 +0x2c
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]: github.com/ledgerwatch/erigon/eth/borfinality.borVerify({0x2e57b70?, 0xc000eca770?}, 0xc0efc55420, 0x2fd2560, 0x2fd2575, {0xc1118dc3c2, >
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]:         github.com/ledgerwatch/erigon/eth/borfinality/bor_checkpoint_verifier.go:92 +0x516
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]: github.com/ledgerwatch/erigon/eth/borfinality.fetchWhitelistMilestone({0x2e57b70, 0xc000eca770}, {0x2e69d10?, 0xc105682e40?}, 0xc111957e>
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]:         github.com/ledgerwatch/erigon/eth/borfinality/whitelist_helpers.go:85 +0x67b
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]: github.com/ledgerwatch/erigon/eth/borfinality.handleMilestone({0x2e57b70?, 0xc000eca770?}, {0x2e69d10?, 0xc105682e40?}, 0x800?)
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]:         github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:172 +0x75
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]: github.com/ledgerwatch/erigon/eth/borfinality.retryHeimdallHandler(0x2b3fca0, 0xc0efc55420, 0x124c3e5?, 0xc0d671e5a0?, {0x26d32be, 0x13})
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]:         github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:118 +0xcb
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]: github.com/ledgerwatch/erigon/eth/borfinality.RetryHeimdallHandler(...)
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]:         github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:100
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]: github.com/ledgerwatch/erigon/eth/borfinality.startMilestoneWhitelistService(0xc10cbb92c0?)
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]:         github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:76 +0x3f
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]: created by github.com/ledgerwatch/erigon/eth/borfinality.Whitelist in goroutine 1
Nov 19 20:56:14 polygon-archive-de-1 erigon[773773]:         github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:47 +0x245
````

**Comment by AskAlexSharov** [comment]
i think it's fixed in later versions (no such file as `bor_checkpoint_verifier.go` now) -  try upgrade

**Comment by AskAlexSharov** [comment]
hmm... anyway seems there is several similar places:
https://github.com/ledgerwatch/erigon/pull/8787
https://github.com/ledgerwatch/erigon/pull/8788
https://github.com/ledgerwatch/erigon/pull/8791

**Comment by zhy827827** [comment]
erigon version 2.57.0  
has same issues @AskAlexSharov 

```
Jan 22 10:08:31 rockx-mainnet-polygon-ovh-node-03 erigon[3126103]: [INFO] [01-22|10:08:31.772] new subscription to logs established
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 erigon[3126071]: github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).fromDB(0xc00115a280, {0x336cae0, 0xc001154460}, {0x338e398?, 0xc00111a8a0}, {0x338e398?, 0xc00111aa80?})
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 erigon[3126071]:         /go/src/github.com/ledgerwatch/erigon/erigon-lib/txpool/pool.go:2093 +0x8b0
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 erigon[3126071]: github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).Start.func1({0x338e398, 0xc00111a8a0})
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 erigon[3126071]:         /go/src/github.com/ledgerwatch/erigon/erigon-lib/txpool/pool.go:327 +0xfe
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 erigon[3126071]: github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).View(0x29e8d60800?, {0x336cae0?, 0xc001154460?}, 0xc0005d4020)
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 erigon[3126071]:         /go/src/github.com/ledgerwatch/erigon/erigon-lib/kv/mdbx/kv_mdbx.go:749 +0xa6
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 erigon[3126071]: github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).Start(0xc00115a280, {0x336cae0?, 0xc001154460}, {0x3381e50, 0xc000960fc0})
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 erigon[3126071]:         /go/src/github.com/ledgerwatch/erigon/erigon-lib/txpool/pool.go:317 +0xc9
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 erigon[3126071]: github.com/ledgerwatch/erigon-lib/txpool.MainLoop({0x336cae0?, 0xc001154460}, {0x3381e50, 0xc000960fc0}, 0xc00115a280, 0xc0007174a0, 0xc000768190, 0xc0011120d8, 0x>
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 erigon[3126071]:         /go/src/github.com/ledgerwatch/erigon/erigon-lib/txpool/pool.go:1727 +0x205
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 erigon[3126071]: created by github.com/ledgerwatch/erigon/eth.New
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 erigon[3126071]:         /go/src/github.com/ledgerwatch/erigon/eth/backend.go:714 +0x3f5d
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 systemd[1]: erigon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 22 10:08:28 rockx-mainnet-polygon-ovh-node-03 systemd[1]: erigon.service: Failed with result 'exit-code'.
Jan 22 10:08:29 rockx-mainnet-polygon-ovh-node-03 systemd[1]: erigon.service: Scheduled restart job, restart counter is at 3.
Jan 22 10:08:29 rockx-mainnet-polygon-ovh-node-03 systemd[1]: Stopped erigon.
Jan 22 10:08:29 rockx-mainnet-polygon-ovh-node-03 systemd[1]: Started erigon.
```

**Comment by AskAlexSharov** [comment]
@mh0lt maybe `consensus/misc/eip1559.go` after `rawdb.ReadHeaderByHash` need nil-header check

**Comment by antonis19** [comment]
@Snawoot  could you check again with Erigon v2.60.5 ?
