### ISSUE TITLE
devnet: handleRootHeaderBlock panics on nil pendingCheckpoint

### ISSUE THREAD

**Issue by battlmonstr** [erigontech/erigon#9290]
Examples:
https://github.com/ledgerwatch/erigon/actions/runs/7557202773/job/20575895087
https://github.com/ledgerwatch/erigon/actions/runs/7613550043/job/20733699538
https://github.com/ledgerwatch/erigon/actions/runs/7625852389/job/20771003924

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x23b9a7f]

goroutine 2157 [running]:
github.com/ledgerwatch/erigon/cmd/devnet/services/polygon.(*Heimdall).handleRootHeaderBlock(0xc0005f1cc0, 0xc000ffc300)
	github.com/ledgerwatch/erigon/cmd/devnet/services/polygon/checkpoint.go:571 +0x73f
github.com/ledgerwatch/erigon/cmd/devnet/services/polygon.(*Heimdall).startRootHeaderBlockSubscription(0xc0005f1cc0)
	github.com/ledgerwatch/erigon/cmd/devnet/services/polygon/checkpoint.go:150 +0x21a
created by github.com/ledgerwatch/erigon/cmd/devnet/services/polygon.(*Heimdall).NodeStarted.func1
	github.com/ledgerwatch/erigon/cmd/devnet/services/polygon/heimdall.go:347 +0x733
FAIL	github.com/ledgerwatch/erigon/cmd/devnet/tests	395.457s
```

**Comment by taratorio** [comment]
devnet has been sunset in favour of kurtosis
